/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppRegistrationsRouteImport } from './routes/app/registrations'
import { Route as AppEventsRouteImport } from './routes/app/events'
import { Route as AppCheckInRouteImport } from './routes/app/check-in'
import { Route as AppEventsIndexRouteImport } from './routes/app/events.index'
import { Route as AppEventsEventIdRouteImport } from './routes/app/events.$eventId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRegistrationsRoute = AppRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckInRoute = AppCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventsRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/app/check-in': typeof AppCheckInRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/registrations': typeof AppRegistrationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/': typeof AppEventsIndexRoute
}
export interface FileRoutesByTo {
  '/app/check-in': typeof AppCheckInRoute
  '/app/registrations': typeof AppRegistrationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/app': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events': typeof AppEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/app/check-in': typeof AppCheckInRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/registrations': typeof AppRegistrationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/': typeof AppEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/app/check-in'
    | '/app/events'
    | '/app/registrations'
    | '/auth/login'
    | '/app/'
    | '/app/events/$eventId'
    | '/app/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/check-in'
    | '/app/registrations'
    | '/auth/login'
    | '/app'
    | '/app/events/$eventId'
    | '/app/events'
  id:
    | '__root__'
    | '/app'
    | '/app/check-in'
    | '/app/events'
    | '/app/registrations'
    | '/auth/login'
    | '/app/'
    | '/app/events/$eventId'
    | '/app/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/registrations': {
      id: '/app/registrations'
      path: '/registrations'
      fullPath: '/app/registrations'
      preLoaderRoute: typeof AppRegistrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/check-in': {
      id: '/app/check-in'
      path: '/check-in'
      fullPath: '/app/check-in'
      preLoaderRoute: typeof AppCheckInRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppEventsRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppEventsRoute
    }
  }
}

interface AppEventsRouteChildren {
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppEventsRouteChildren: AppEventsRouteChildren = {
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppEventsRouteWithChildren = AppEventsRoute._addFileChildren(
  AppEventsRouteChildren,
)

interface AppRouteChildren {
  AppCheckInRoute: typeof AppCheckInRoute
  AppEventsRoute: typeof AppEventsRouteWithChildren
  AppRegistrationsRoute: typeof AppRegistrationsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckInRoute: AppCheckInRoute,
  AppEventsRoute: AppEventsRouteWithChildren,
  AppRegistrationsRoute: AppRegistrationsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
