export * from "./events.route";
export * from "./auth.route";
export * from "./team.route";
export * from "./user.route";
export * from "./payments.route";
export * from "./coupons.route";
export * from "./colleges.route";
export * from "./organizer.route";
export * from "./ops.route";
